# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: stats.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'stats.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0bstats.proto\x12\x05stats\x1a\x1bgoogle/protobuf/empty.proto\"\x18\n\x06PostId\x12\x0e\n\x06postId\x18\x01 \x01(\t\"\x18\n\x06UserId\x12\x0e\n\x06userId\x18\x01 \x01(\t\"\'\n\tDateCount\x12\x0b\n\x03\x64\x61y\x18\x01 \x01(\t\x12\r\n\x05\x63ount\x18\x02 \x01(\x03\"8\n\x06Totals\x12\r\n\x05views\x18\x01 \x01(\x03\x12\r\n\x05likes\x18\x02 \x01(\x03\x12\x10\n\x08\x63omments\x18\x03 \x01(\x03\",\n\nTimeSeries\x12\x1e\n\x04\x64\x61ta\x18\x01 \x03(\x0b\x32\x10.stats.DateCount\"d\n\nTopRequest\x12(\n\x06metric\x18\x01 \x01(\x0e\x32\x18.stats.TopRequest.Metric\",\n\x06Metric\x12\t\n\x05VIEWS\x10\x00\x12\t\n\x05LIKES\x10\x01\x12\x0c\n\x08\x43OMMENTS\x10\x02\"*\n\x08TopPosts\x12\x1e\n\x07postIds\x18\x01 \x03(\x0b\x32\r.stats.PostId\"*\n\x08TopUsers\x12\x1e\n\x07userIds\x18\x01 \x03(\x0b\x32\r.stats.UserId2\xca\x02\n\x0cStatsService\x12)\n\tGetTotals\x12\r.stats.PostId\x1a\r.stats.Totals\x12\x36\n\x12GetViewsTimeSeries\x12\r.stats.PostId\x1a\x11.stats.TimeSeries\x12\x36\n\x12GetLikesTimeSeries\x12\r.stats.PostId\x1a\x11.stats.TimeSeries\x12\x39\n\x15GetCommentsTimeSeries\x12\r.stats.PostId\x1a\x11.stats.TimeSeries\x12\x31\n\x0bGetTopPosts\x12\x11.stats.TopRequest\x1a\x0f.stats.TopPosts\x12\x31\n\x0bGetTopUsers\x12\x11.stats.TopRequest\x1a\x0f.stats.TopUsersb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'stats_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_POSTID']._serialized_start=51
  _globals['_POSTID']._serialized_end=75
  _globals['_USERID']._serialized_start=77
  _globals['_USERID']._serialized_end=101
  _globals['_DATECOUNT']._serialized_start=103
  _globals['_DATECOUNT']._serialized_end=142
  _globals['_TOTALS']._serialized_start=144
  _globals['_TOTALS']._serialized_end=200
  _globals['_TIMESERIES']._serialized_start=202
  _globals['_TIMESERIES']._serialized_end=246
  _globals['_TOPREQUEST']._serialized_start=248
  _globals['_TOPREQUEST']._serialized_end=348
  _globals['_TOPREQUEST_METRIC']._serialized_start=304
  _globals['_TOPREQUEST_METRIC']._serialized_end=348
  _globals['_TOPPOSTS']._serialized_start=350
  _globals['_TOPPOSTS']._serialized_end=392
  _globals['_TOPUSERS']._serialized_start=394
  _globals['_TOPUSERS']._serialized_end=436
  _globals['_STATSSERVICE']._serialized_start=439
  _globals['_STATSSERVICE']._serialized_end=769
# @@protoc_insertion_point(module_scope)
