# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import stats_pb2 as stats__pb2

GRPC_GENERATED_VERSION = '1.71.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in stats_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class StatsServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetTotals = channel.unary_unary(
                '/stats.StatsService/GetTotals',
                request_serializer=stats__pb2.PostId.SerializeToString,
                response_deserializer=stats__pb2.Totals.FromString,
                _registered_method=True)
        self.GetViewsTimeSeries = channel.unary_unary(
                '/stats.StatsService/GetViewsTimeSeries',
                request_serializer=stats__pb2.PostId.SerializeToString,
                response_deserializer=stats__pb2.TimeSeries.FromString,
                _registered_method=True)
        self.GetLikesTimeSeries = channel.unary_unary(
                '/stats.StatsService/GetLikesTimeSeries',
                request_serializer=stats__pb2.PostId.SerializeToString,
                response_deserializer=stats__pb2.TimeSeries.FromString,
                _registered_method=True)
        self.GetCommentsTimeSeries = channel.unary_unary(
                '/stats.StatsService/GetCommentsTimeSeries',
                request_serializer=stats__pb2.PostId.SerializeToString,
                response_deserializer=stats__pb2.TimeSeries.FromString,
                _registered_method=True)
        self.GetTopPosts = channel.unary_unary(
                '/stats.StatsService/GetTopPosts',
                request_serializer=stats__pb2.TopRequest.SerializeToString,
                response_deserializer=stats__pb2.TopPosts.FromString,
                _registered_method=True)
        self.GetTopUsers = channel.unary_unary(
                '/stats.StatsService/GetTopUsers',
                request_serializer=stats__pb2.TopRequest.SerializeToString,
                response_deserializer=stats__pb2.TopUsers.FromString,
                _registered_method=True)


class StatsServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetTotals(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetViewsTimeSeries(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetLikesTimeSeries(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetCommentsTimeSeries(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetTopPosts(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetTopUsers(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_StatsServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetTotals': grpc.unary_unary_rpc_method_handler(
                    servicer.GetTotals,
                    request_deserializer=stats__pb2.PostId.FromString,
                    response_serializer=stats__pb2.Totals.SerializeToString,
            ),
            'GetViewsTimeSeries': grpc.unary_unary_rpc_method_handler(
                    servicer.GetViewsTimeSeries,
                    request_deserializer=stats__pb2.PostId.FromString,
                    response_serializer=stats__pb2.TimeSeries.SerializeToString,
            ),
            'GetLikesTimeSeries': grpc.unary_unary_rpc_method_handler(
                    servicer.GetLikesTimeSeries,
                    request_deserializer=stats__pb2.PostId.FromString,
                    response_serializer=stats__pb2.TimeSeries.SerializeToString,
            ),
            'GetCommentsTimeSeries': grpc.unary_unary_rpc_method_handler(
                    servicer.GetCommentsTimeSeries,
                    request_deserializer=stats__pb2.PostId.FromString,
                    response_serializer=stats__pb2.TimeSeries.SerializeToString,
            ),
            'GetTopPosts': grpc.unary_unary_rpc_method_handler(
                    servicer.GetTopPosts,
                    request_deserializer=stats__pb2.TopRequest.FromString,
                    response_serializer=stats__pb2.TopPosts.SerializeToString,
            ),
            'GetTopUsers': grpc.unary_unary_rpc_method_handler(
                    servicer.GetTopUsers,
                    request_deserializer=stats__pb2.TopRequest.FromString,
                    response_serializer=stats__pb2.TopUsers.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'stats.StatsService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('stats.StatsService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class StatsService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetTotals(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/stats.StatsService/GetTotals',
            stats__pb2.PostId.SerializeToString,
            stats__pb2.Totals.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetViewsTimeSeries(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/stats.StatsService/GetViewsTimeSeries',
            stats__pb2.PostId.SerializeToString,
            stats__pb2.TimeSeries.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetLikesTimeSeries(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/stats.StatsService/GetLikesTimeSeries',
            stats__pb2.PostId.SerializeToString,
            stats__pb2.TimeSeries.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetCommentsTimeSeries(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/stats.StatsService/GetCommentsTimeSeries',
            stats__pb2.PostId.SerializeToString,
            stats__pb2.TimeSeries.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetTopPosts(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/stats.StatsService/GetTopPosts',
            stats__pb2.TopRequest.SerializeToString,
            stats__pb2.TopPosts.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetTopUsers(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/stats.StatsService/GetTopUsers',
            stats__pb2.TopRequest.SerializeToString,
            stats__pb2.TopUsers.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
