syntax = "proto3";

package postservice;

message Post {
  string id = 1;
  string title = 2;
  string description = 3;
  string creatorId = 4;
  bool isPrivate = 5;
  repeated string tags = 6;
  string createdAt = 7;
  string updatedAt = 8;
}

// Для создания
message CreateUpdatePostRequest {
  string title = 1;
  string description = 2;
  string creatorId = 3;
  bool isPrivate = 4;
  repeated string tags = 5;
}

message PostResponse {
  Post post = 1;
}

message GetDeletePostRequest {
  string id = 1;
}

message ListPostsRequest {
  int32 page = 1;
  int32 pageSize = 2;
}

message ListPostsResponse {
  repeated Post posts = 1;
  int32 totalCount = 2;
}

service PostService {
  rpc CreatePost(CreateUpdatePostRequest) returns (PostResponse);
  rpc GetPost(GetDeletePostRequest) returns (PostResponse);
  rpc UpdatePost(CreateUpdatePostRequest) returns (PostResponse);
  rpc DeletePost(GetDeletePostRequest) returns (PostResponse);
  rpc ListPosts(ListPostsRequest) returns (ListPostsResponse);
}